services:
  db:
    image: ibmcom/db2
    restart: always
    environment:
      name: mydb2
      privileged: true
      LICENSE: accept
      DB2INST1_PASSWORD: HariboMachtKinderFroh
      DBNAME: testdb
    ports: 
      - 50000:50000